fixes
DBTrenches/tsqlscheduler pull request #3
Opened 2020-04-09 15:32 UTC by Morshedk

2020-04-09 15:41 UTC, taddison requested changes
Can you either add a gitignore for the file ` .vs/slnx.sqlite ` or delete it locally if it's not used.  Doesn't need to be in the repo.

2020-04-09 15:41 UTC, taddison commented on src/tsqlScheduler/Public/Set-DatabaseTask.ps1
> +$Task
What does this do - is it for debugging?

2020-04-09 15:45 UTC, petervandivier reviewed
prob wanna .gitignore the .sqlite file (you can also ignore local-only by adding it to `.git/info/exclude`

if you guys have any time/interest in adding a whole-module dependency to the project as well, `Invoke-DbaQuery` supports parameterised queries (to skip out on the `.Replace()` tickery :-p

2020-04-09 20:38 UTC, taddison commented
Added the gitignore entry and removed the file.

Aiming to limit dependencies as long as possible, but that `replace` is pretty ugly.

2020-04-09 20:38 UTC, taddison approved these changes

2020-04-09 20:38 UTC, merged

2020-04-10 13:05 UTC, petervandivier commented
fwiw - https://github.com/sqlcollaborative/Invoke-SqlCmd2 supports it as well and is obviously way lighter weight than dbatools proper